### ISSUE TITLE
选择1后输入Luo报错Luo not defined

### ISSUE THREAD

**Issue by ethanyoung** [mluo666/Exercises#1]
该行总是报错：

```py
newName = input("Please enter a name to add:")
```

错误日志：
```sh
$ python names.py
====================
     Name System
1: add a name
2: delete a name
3: modify a name
4: search a name
====================
Please enter your choice:1
Please enter a name to add:Luo
Traceback (most recent call last):
  File "names.py", line 41, in <module>
    newName = input("Please enter a name to add:")
  File "<string>", line 1, in <module>
NameError: name 'Luo' is not defined
```

**Comment by ethanyoung** [comment]
1. 如果成功，返回增删改查后的名字，如果失败则返回空
2. 老问题，你要用 `raw_input`，`input`是Python3用的。
3. 本来就逻辑很简单，目前不需要简化。

**Comment by mluo666** [comment]
有个概念不是很清楚，有点模糊。列表的方法操作后，有的改变原列表，返回新列表；有的不改变原列表，返回新列表？这个程序里哪里需要注意吗？

**Comment by ethanyoung** [comment]
需要将 `input` 改为 `raw_input`，如下：

```py
newName = raw_input("Please enter a name to add:")
```

**Comment by mluo666** [comment]
soga
